### ISSUE TITLE
convertKey operation empties "key" field in windowed(struct)

### ISSUE THREAD

**Issue by jeroenvandisseldorp** [Axual/ksml#240]
When performing a converKey after an aggregate operation, the key field is emptied.

Reproduce through the following topology (modified version of 09-example-aggregate.yaml):

```
streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
    offsetResetPolicy: latest

pipelines:
  main:
    from: sensor_source
    via:
      - type: groupBy
        name: group_by_owner2
        mapper:
          code: |
            if value is None or not "owner" in value:
              return {'key':'no owner'}
          expression: "{'key':value['owner']}"
          resultType: json
      - type: windowByTime
        windowType: tumbling
        duration: 20s
      - type: aggregate
        store:
          name: mystep
          type: window
          windowSize: 10m
          retention: 1h
          caching: false
        initializer:
          expression: 0
          resultType: long
        aggregator:
          expression: aggregatedValue+1
      - type: toStream
      - type: peek
        forEach:
          code: log.info("BEFORE CONVERT - key={}, value={}", key, value)
      - type: convertKey
        into: json:windowed(struct)
      - type: peek
        forEach:
          code: log.info("AFTER CONVERT - key={}, value={}", key, value)
```

The output will contain the following:

```
2025-06-19T14:55:24,135Z INFO  a.f.pipelines_main_via_step5_forEach BEFORE CONVERT - key={'end': 1750344940000, 'endTime': '2025-06-19T14:55:40Z', 'key': {'key': 'Dave'}, 'start': 1750344920000, 'startTime': '2025-06-19T14:55:20Z', '@schema': {'type': 'struct', 'namespace': 'io.axual.ksml.data', 'name': 'WindowedStruct', 'doc': 'Windowed Struct', 'fields': [{'name': 'start', 'doc': 'Start timestamp', 'required': True, 'constant': False, 'tag': -1, 'type': 'long', 'order': 'ASCENDING'}, {'name': 'end', 'doc': 'End timestamp', 'required': True, 'constant': False, 'tag': -1, 'type': 'long', 'order': 'ASCENDING'}, {'name': 'startTime', 'doc': 'Start time', 'required': True, 'constant': False, 'tag': -1, 'type': 'string', 'order': 'ASCENDING'}, {'name': 'endTime', 'doc': 'End time', 'required': True, 'constant': False, 'tag': -1, 'type': 'string', 'order': 'ASCENDING'}, {'name': 'key', 'doc': 'Window key', 'required': True, 'constant': False, 'tag': -1, 'type': {'type': 'struct', 'name': 'AnonymousStructSchema', 'fields': []}, 'order': 'ASCENDING'}]}, '@type': 'WindowedStruct'}, value=1
2025-06-19T14:55:24,139Z INFO  a.f.pipelines_main_via_step7_forEach AFTER CONVERT - key={'end': 1750344940000, 'endTime': '2025-06-19T14:55:40Z', 'key': {}, 'start': 1750344920000, 'startTime': '2025-06-19T14:55:20Z', '@schema': {'type': 'struct', 'namespace': 'io.axual.ksml.data', 'name': 'WindowedStruct', 'doc': 'Windowed Struct', 'fields': [{'name': 'start', 'doc': 'Start timestamp', 'required': True, 'constant': False, 'tag': -1, 'type': 'long', 'order': 'ASCENDING'}, {'name': 'end', 'doc': 'End timestamp', 'required': True, 'constant': False, 'tag': -1, 'type': 'long', 'order': 'ASCENDING'}, {'name': 'startTime', 'doc': 'Start time', 'required': True, 'constant': False, 'tag': -1, 'type': 'string', 'order': 'ASCENDING'}, {'name': 'endTime', 'doc': 'End time', 'required': True, 'constant': False, 'tag': -1, 'type': 'string', 'order': 'ASCENDING'}, {'name': 'key', 'doc': 'Window key', 'required': True, 'constant': False, 'tag': -1, 'type': {'type': 'struct', 'name': 'AnonymousStructSchema', 'fields': []}, 'order': 'ASCENDING'}]}, '@type': 'WindowedStruct'}, value=1
```

Note how the key field has changed from `'key': {'key': 'Dave'}` to `'key': {}`. This is a conversion bug.
