### ISSUE TITLE
Error processing a message with key NULL.

### ISSUE THREAD

**Issue by hclbaur** [Axual/ksml#47]
I am not 100% sure what is causing this error in the ksml/runner and also not why it is referring to a Json deserialiser:

`Caused by: io.axual.ksml.exception.KSMLExecutionException: Error while executing the Kafka Streams topology: Json serde not found for data type null`

I believe it has to do with the fact that the message has no key (or a key with a null value). 
The message looks like this (in message browser in the Axual Self-service environment):

````
"message":{
"partition":4
"offset":951
"timestamp":1652912264843
"headers":[...]
"value":
"0000000911020e43524541544544021a4d6574657252656164696e6773021470352d70..."
"key":NULL
}
````

The key is NULL and the value is a binary string.  I configured the KSML app like this, with keyType none and valueType bytes:

````
streams:
  p5meterresponse:
    topic: APP9329_LianderP5MeterResponse
    keyType: none
    valueType: bytes

functions:
  print_message:
    type: forEach
    code: "print('key='+(key if isinstance(key,str) else str(key))+', value='+(value if isinstance(value,str) else str(value)))"

pipelines:
  main:
    from: p5meterresponse
    forEach: print_message
````

I also tried keyType string but then I see a null pointer exception when reading the message.

The message we are trying to read is actually an Avro message from the Liander platform, but for demo purpose I would like to read it as a binary type.
